function forget_password()
{
$action = request('action');
$message = '';
if($action == "forget")
{
$email = $_POST["email"];
//debug($email);
if($email)
{
$db = new db2();
$sql = "select * from participant where email like '".filter_var($email, FILTER_SANITIZE_EMAIL)."'";
$participant = $db->result($sql, 1);
//debug_r($participant);
if($participant)
{
//generate and send participant reset password link
$reset_id = md5(session_id().time());
//debug($reset_id);
$link = BASE_URL.'reset_password.php?id='.$reset_id;
$body = 'Dear '.$participant['name'].',
<p>Kindly note that a request for reset password has been generated by you, click the following link to reset your
    password. In case you have not generated the request kindly ignore this email.</p>
<a href="'.$link.'">Reset Password</a>
<p>&nbsp;</p>
<p>Dated: '.date("r").'</p>';
//$participant["email"] = SITE_ADMIN_EMAIL;
$email = $participant["email"];
$subject = 'Reset Password Request | iGap - International Ghadeer Awareness Program';
$attachments = '';
//debug_r($participant["email"]);
email($email, $subject, $body, $attachments);
//debug_r("Email sent");
$sql_update = "update participant set reset_link = '".$reset_id."' WHERE id = ".$participant["id"];
$db->sqlq($sql_update);
// debug_r($sql_update);
redirect("?action=success");
}
redirect("?action=not_found");
}
}
elseif($action == "success")
{
$message = '<p style="background:#CFC;">A password reset link has been sent to your email. Please check your inbox as
    well as junk folder.</p>';
}
elseif($action == "not_found")
$message = '<p style="background:#FCC;">If an account matching the provided details exists, we will send a password
    reset link. Please check your inbox.</p>';
// debug_r($action);
$temp = '
<div class="traveltour-page-title-wrap container traveltour-style-custom traveltour-left-align">
    <div class="traveltour-header-transparent-substitute" style="height: 17px;"></div>
    <div class="traveltour-page-title-overlay"></div>
    <div class="traveltour-page-title-container traveltour-container">
        <div class="traveltour-page-title-content traveltour-item-pdlr">
            <h1 class="traveltour-page-title">Forget Password</h1>
        </div>
    </div>
</div>

<div class="traveltour-page-wrapper" id="traveltour-page-wrapper">
    <div class="tourmaster-template-wrapper">
        <div class="tourmaster-container">
            <div class="tourmaster-page-content tourmaster-login-template-content container tourmaster-item-pdlr">';

                if($message) {
                $temp .= '<div class="tourmaster-notification-box tourmaster-failure">'.$message.'</div>';
                }
                $temp .= 'To reset your password, please enter your email address below
                <form class="tourmaster-login-form tourmaster-form-field tourmaster-with-border" method="post"
                    action="forget_password.php?action=forget">
                    <div class="tourmaster-login-form-fields clearfix">
                        <p class="tourmaster-login-user"><input type="email" name="email" placeholder="Email" required>
                        </p>
                        <p class="tourmaster-login-submit">
                            <input type="submit" name="wp-submit" class="btn btn-success hover btn-small mt-25"
                                value="Reset My Password">
                            <input type="button" name="wp-register" style="background-color:#a4704a"
                                class="btn btn-success hover btn-small mt-25" onclick="location.href=\'register\'"
                                value="SIGN UP">
                            <span class="tourmaster-login-lost-password"><a href="login.php">SIGN IN</a></span>
                    </div>
                </form>
            </div>
        </div>
    </div>';
    $head = '<style>
    h1.traveltour-page-title {
        text-align: center;
        text-transform: uppercase;
        font-size: 30px;
        font-weight: bold;
        letter-spacing: 1px;
    }

    .tourmaster-template-wrapper {
        text-align: center;
    }

    .tourmaster-template-wrapper input[type=text],
    .tourmaster-template-wrapper input[type=email],
    .tourmaster-template-wrapper input[type=password] {
        width: 400px;
        height: 40px;
        margin-top: 15px;
    }

    .tourmaster-login-submit {
        width: 400px;
        margin: 0 auto;
        text-align: left;
    }

    .tourmaster-login-submit input {
        border-radius: 0;
        margin-right: 10px;
        padding: 10px 20px;
    }

    .tourmaster-login-lost-password {
        text-align: right;
        float: right;
        line-height: 112px;
        color: black;
    }

    .tourmaster-login-lost-password a {
        color: black;
        text-decoration: underline;
        font-size: 14px;
    }
    </style>';
    $data_n = array();
    $data_n["html_foot"] = $head;
    $data_n["html_title"] = "Forget Password";
    $data_n["html_heading"] = "Forget Password";
    // $data_n["html_banner"] = 'igap/images/banner-01.jpg';
    $data_n['html_text'] = $temp;
    return $data_n;
    }
    function reset_password()
    {
    $id = request("id");
    $participant = get_tuple("participant", $id, 'reset_link');
    if($participant)
    {
    if(request("new_password") == "")
    {
    alert("The requried fields are missing");
    redirect("reset_password.php?id=".$id);
    }
    if(request("new_password") == request("confirm_password"))
    {

    }
    $temp = '
    <div class="traveltour-page-title-wrap container traveltour-style-custom traveltour-left-align">
        <div class="traveltour-header-transparent-substitute" style="height: 17px;"></div>
        <div class="traveltour-page-title-overlay"></div>
        <div class="traveltour-page-title-container traveltour-container">
            <div class="traveltour-page-title-content traveltour-item-pdlr">
                <h1 class="traveltour-page-title">Forget Password</h1>
            </div>
        </div>
    </div>

    <div class="traveltour-page-wrapper" id="traveltour-page-wrapper">
        <div class="tourmaster-template-wrapper">
            <div class="tourmaster-container">
                <div class="tourmaster-page-content tourmaster-login-template-content container tourmaster-item-pdlr">';

                    // if($message) {
                    // $temp .= '<div class="tourmaster-notification-box tourmaster-failure">'.$message.'</div>';
                    // }
                    $temp .= '
                    To reset your password, please enter your new password below
                    <form class="tourmaster-login-form tourmaster-form-field tourmaster-with-border" method="post"
                        action="reset_password.php?action=reset_password&id='.$_GET[" id"].'" autocomplete="off">
                        <div class="tourmaster-login-form-fields clearfix">
                            <p class="tourmaster-login-user"><input type="password" name="new_password"
                                    placeholder="New Password" required autocomplete="off"></p>
                            <p class="tourmaster-login-user"><input type="password" name="confirm_password"
                                    placeholder="Confirm Password" required autocomplete="off"></p>
                            <p class="tourmaster-login-submit">
                                <input type="submit" name="wp-submit" class="btn btn-success hover btn-small mt-25"
                                    value="Reset My Password">
                                <input type="button" name="wp-register" style="background-color:#a4704a"
                                    class="btn btn-success hover btn-small mt-25" onclick="location.href=\'register\'"
                                    value="SIGN UP">
                                <span class="tourmaster-login-lost-password"><a href="login.php">SIGN IN</a></span>
                        </div>
                    </form>
                </div>
            </div>
        </div>';
        $head = '<style>
        h1.traveltour-page-title {
            text-align: center;
            text-transform: uppercase;
            font-size: 30px;
            font-weight: bold;
            letter-spacing: 1px;
        }

        .tourmaster-template-wrapper {
            text-align: center;
        }

        .tourmaster-template-wrapper input[type=text],
        .tourmaster-template-wrapper input[type=email],
        .tourmaster-template-wrapper input[type=password] {
            width: 400px;
            height: 40px;
            margin-top: 15px;
        }

        .tourmaster-login-submit {
            width: 400px;
            margin: 0 auto;
            text-align: left;
        }

        .tourmaster-login-submit input {
            border-radius: 0;
            margin-right: 10px;
            padding: 10px 20px;
        }

        .tourmaster-login-lost-password {
            text-align: right;
            float: right;
            line-height: 112px;
            color: black;
        }

        .tourmaster-login-lost-password a {
            color: black;
            text-decoration: underline;
            font-size: 14px;
        }
        </style>';
        }
        else
        {
        $temp = 'Error 400! Invalid Page';
        }
        $data_n = array();
        $data_n["html_foot"] = $head;
        $data_n["html_title"] = "Forget Password";
        $data_n["html_heading"] = "Forget Password";
        // $data_n["html_banner"] = 'igap/images/banner-01.jpg';
        $data_n['html_text'] = $temp;
        return $data_n;
        }